name       : telegram
version    : 4.8.4
release    : 184
source     :
    - https://github.com/telegramdesktop/tdesktop/releases/download/v4.8.4/tdesktop-4.8.4-full.tar.gz : 4328296df07557786e1b9cf22f6675200dbdf29c75d2efeb635c6b7f3f951e8d
    - git|https://github.com/desktop-app/tg_owt.git : dcb5069ff76bd293e86928804208737e6cee2ccc
    - git|https://gitlab.xiph.org/xiph/rnnoise.git : 7f449bf8bd3b933891d12c30112268c4090e4d59
homepage   : https://desktop.telegram.org/
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram Desktop messaging app
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
optimize   :
    - function-sections
    - icf-safe
    - lto
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(absl_base)
    - pkgconfig(alsa)
    - pkgconfig(epoxy)
    - pkgconfig(fmt)
    - pkgconfig(glibmm-2.68)
    - pkgconfig(hunspell)
    - pkgconfig(jemalloc)
    - pkgconfig(libavcodec)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libxxhash)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - pkgconfig(protobuf) # For the bundles cdl3 library.
    - pkgconfig(vpx)
    - pkgconfig(wayland-server)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(wayland-protocols)
    - gobject-introspection
    - kimageformats
    - libboost-devel
    - libdispatch-devel
    - plasma-wayland-protocols
    - yasm
rundeps    :
    - qt6-imageformats
setup      : |
    cp -r $sources/tg_owt.git tg_owt
    pushd tg_owt
        %patch -p1 < $pkgfiles/cstdint.patch
        %cmake_ninja -DTG_OWT_DLOPEN_PIPEWIRE=OFF
        %ninja_build
    popd

    cp -r $sources/rnnoise.git rnnoise
    pushd rnnoise
        %autogen \
            --disable-doc \
            --disable-examples \
            --disable-shared \
            --libdir=$PWD/installed/lib \
            --prefix=$PWD/installed
        %make
        %make_install DESTDIR=/
    popd

    %patch -p1 < $pkgfiles/cstdint2.patch
    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$workdir/rnnoise/installed/lib/pkgconfig"
    %cmake_ninja \
        -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
        -DDESKTOP_APP_DISABLE_JEMALLOC=ON \
        -DTDESKTOP_API_HASH=8562eb11c58f218ac08ee12c32e07ece \
        -DTDESKTOP_API_ID=1080918 \
        -DTDESKTOP_LAUNCHER_BASENAME=telegramdesktop \
        -Dtg_owt_DIR=$workdir/tg_owt/solusBuildDir
build      : |
    %ninja_build
install    : |
    %ninja_install
