name       : telegram
version    : 1.8.4
release    : 121
source     :
    - https://updates.tdesktop.com/tlinux/tsetup.1.8.4.tar.xz : 567e008f59f35545e046a6f0297dd148294129713cde509498e1ad01c69dfaa4
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xcb)
install    : |
    install -D -m 00755 Telegram $installdir/usr/bin/telegram-desktop
    install -Dm00644 $pkgfiles/telegramdesktop.desktop $installdir/usr/share/applications/telegramdesktop.desktop
    # Install icons
    for icon_size in 16 32 128 256 512
    do
        install -D -m00644 $pkgfiles/icon_${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/telegram.png
    done
