name       : telegram
version    : 2.5.8
release    : 142
source     :
    - https://github.com/telegramdesktop/tdesktop/releases/download/v2.5.8/tdesktop-2.5.8-full.tar.gz : 9c89cb31f8ba8a26821fe3c2769b04162e8d7629d327f9cd25a892e88878417e
    - git|https://github.com/desktop-app/tg_owt.git : be23804afce3bb2e80a1d57a7c1318c71b82b7de
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(alsa)
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(enchant-2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hunspell)
    - pkgconfig(libavcodec)
    - pkgconfig(libjpeg)
    - pkgconfig(libpulse)
    - pkgconfig(liblz4)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(vpx)
    - pkgconfig(xcb-keysyms)
    - kwayland-devel
    - range-v3
    - xxhash-devel
    - yasm
rundeps    :
    - qt5-imageformats
setup      : |
    cp -r $sources/tg_owt.git tg_owt
    pushd tg_owt
        # tg_out uses unreleased features of libvpx, so we cannot link it against
        # the one in our repo (using the patch provided in this package). Until a new version
        # is not released, use the bundled libvpx with git submodules.
        %cmake_ninja -DBUILD_SHARED_LIBS=NO # We want Telegram to statically link to tg_owt.
        %ninja_build
    popd

    %cmake_ninja \
        -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
        -DTDESKTOP_API_HASH=8562eb11c58f218ac08ee12c32e07ece \
        -DTDESKTOP_API_ID=1080918 \
        -DTDESKTOP_LAUNCHER_BASENAME=telegramdesktop \
        -Dtg_owt_DIR=$workdir/tg_owt/solusBuildDir
build      : |
    %ninja_build
install    : |
    %ninja_install
