name       : telegram
version    : 2.5.1
release    : 141
source     :
    - https://github.com/telegramdesktop/tdesktop/releases/download/v2.5.1/tdesktop-2.5.1-full.tar.gz : f1cc5e876deaa4fa4eaafbba95f127d5a3114c166802902b8584099852b9eae2
    - https://github.com/desktop-app/tg_owt/archive/75ac66937341d8a9207375aaee79b4bdc500146c/tg_owt.tar.gz : 6e27cf6d8997630d04c45e15b654a91d3703a6726d5e09399c4795c8c330fe55
    - git|https://chromium.googlesource.com/libyuv/libyuv.git : 058746415698c6e101442c2b3e95f50832281671
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(alsa)
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(enchant-2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hunspell)
    - pkgconfig(libavcodec)
    - pkgconfig(libjpeg)
    - pkgconfig(libpulse)
    - pkgconfig(liblz4)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - pkgconfig(protobuf)
    - pkgconfig(vpx)
    - pkgconfig(xcb-keysyms)
    - range-v3
    - xxhash-devel
    - yasm
rundeps    :
    - qt5-imageformats
setup      : |
    mkdir tg_owt

    pushd tg_owt
        tar xf $sources/tg_owt.tar.gz --strip-components=1
        %patch -p1 < $pkgfiles/tg_owt-Link-against-shared-libvpx.patch
        rmdir src/third_party/libyuv
        ln -s $sources/libyuv.git src/third_party/libyuv

        %cmake_ninja -DBUILD_SHARED_LIBS=NO # We want Telegram to statically link to tg_owt.
        %ninja_build
    popd

    %cmake_ninja \
        -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
        -DTDESKTOP_API_HASH=8562eb11c58f218ac08ee12c32e07ece \
        -DTDESKTOP_API_ID=1080918 \
        -DTDESKTOP_LAUNCHER_BASENAME=telegramdesktop \
        -Dtg_owt_DIR=$workdir/tg_owt/solusBuildDir
build      : |
    %ninja_build
install    : |
    %ninja_install
