name       : telegram
version    : 1.5.12
release    : 104
source     :
    - https://updates.tdesktop.com/tlinux/tsetup.1.5.12.tar.xz : 12254dfc71d7a80a5012cbb8a76a425ded0e24019b18272e7dbeb4ef134b5954
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xcb)
install    : |
    install -D -m 00755 Telegram $installdir/usr/bin/telegram
    # Install icons
    for icon_size in 16 32 128 256 512
    do
        install -D -m00644 $pkgfiles/icon_${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/telegram.png
    done

    # Desktop File
    rm -f $installdir/usr/share/applications/telegram.desktop
    install -D -m00644 $pkgfiles/telegram.desktop $installdir/usr/share/applications/telegram.desktop
