name       : telegram
version    : 2.1.2
release    : 132
source     :
    - https://github.com/telegramdesktop/tdesktop/releases/download/v2.1.2/tdesktop-2.1.2-full.tar.gz : 444455aa166448c43b46abad604e59f630225962b3fbebb32caccea2993e6858
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Gui)
    - pkgconfig(alsa)
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(enchant-2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hunspell)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(liblz4)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - range-v3
    - xxhash-devel
rundeps    :
    - qt5-imageformats
setup      : |
    %cmake_ninja \
        -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
        -DDESKTOP_APP_USE_PACKAGED_EXPECTED=OFF \
        -DDESKTOP_APP_USE_PACKAGED_GSL=OFF \
        -DDESKTOP_APP_USE_PACKAGED_RLOTTIE=OFF \
        -DDESKTOP_APP_USE_PACKAGED_VARIANT=OFF \
        -DTDESKTOP_API_HASH=8562eb11c58f218ac08ee12c32e07ece \
        -DTDESKTOP_API_ID=1080918 \
        -DTDESKTOP_LAUNCHER_BASENAME=telegramdesktop \
        -DTDESKTOP_USE_PACKAGED_TGVOIP=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
