name       : telegram
version    : 3.6.1
release    : 169
source     :
    - https://github.com/telegramdesktop/tdesktop/releases/download/v3.6.1/tdesktop-3.6.1-full.tar.gz : 1e87df0970b135d566f5af4bc6c2695fc98ba387dc1137100a478f02d48c12e8
    - git|https://github.com/desktop-app/tg_owt.git : a264028ec71d9096e0aa629113c49c25db89d260
    - git|https://gitlab.xiph.org/xiph/rnnoise.git : 7f449bf8bd3b933891d12c30112268c4090e4d59
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
optimize   :
    - function-sections
    - icf-safe
    - lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(absl_base)
    - pkgconfig(alsa)
    - pkgconfig(epoxy)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(hunspell)
    - pkgconfig(jemalloc)
    - pkgconfig(libavcodec)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libxxhash)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - pkgconfig(vpx)
    - pkgconfig(wayland-server)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - kwayland-devel
    - yasm
rundeps    :
    - qt5-imageformats
setup      : |
    cp -r $sources/tg_owt.git tg_owt
    pushd tg_owt
        %cmake_ninja -DTG_OWT_DLOPEN_PIPEWIRE=OFF
        %ninja_build
    popd

    cp -r $sources/rnnoise.git rnnoise
    pushd rnnoise
        %autogen \
            --disable-doc \
            --disable-examples \
            --disable-shared \
            --libdir=$PWD/installed/lib \
            --prefix=$PWD/installed
        %make
        %make_install DESTDIR=/
    popd

    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$workdir/rnnoise/installed/lib/pkgconfig"
    # Building with Qt6 requires compiling and bundling kwayland at the moment. I don't want that.
    %cmake_ninja \
        -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
        -DDESKTOP_APP_QT6=OFF \
        -DTDESKTOP_API_HASH=8562eb11c58f218ac08ee12c32e07ece \
        -DTDESKTOP_API_ID=1080918 \
        -DTDESKTOP_LAUNCHER_BASENAME=telegramdesktop \
        -Dtg_owt_DIR=$workdir/tg_owt/solusBuildDir
build      : |
    %ninja_build
install    : |
    %ninja_install
