name       : telegram
version    : 0.9.1
release    : 26
source     :
    - https://updates.tdesktop.com/tlinux/tsetup.0.9.1.tar.xz : a002c00deb5ad554abf452c1def4f255733b0fe01cdeb08dcfecd1be24899ecc
license    : GPL-3.0
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free. 
description  : |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free. 
builddeps    : wget
install      : |
    mkdir -p %installroot%/usr/bin
    mkdir -p %installroot%/usr/share/applications/
    mv Telegram %installroot%/usr/bin/telegram

    # Create icon directories
    mkdir -p %installroot%/usr/share/icons/hicolor/16x16/apps
    mkdir -p %installroot%/usr/share/icons/hicolor/32x32/apps
    mkdir -p %installroot%/usr/share/icons/hicolor/128x128/apps
    mkdir -p %installroot%/usr/share/icons/hicolor/256x256/apps
    mkdir -p %installroot%/usr/share/icons/hicolor/512x512/apps

    iconlist=(icon_16x16.png icon_32x32.png icon_128x128.png icon_256x256.png icon_512x512.png)

    # Fetch all icons

    for icon in "${iconlist[@]}"
    do
        wget https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/Telegram/Telegram/Images.xcassets/Icon.iconset/$icon

        icondir=${icon/icon_/}
        icondir=${icondir/.png/}

        mv $icon %installroot%/usr/share/icons/hicolor/$icondir/apps/telegram.png
    done

    rm -f %installroot%/usr/share/applications/telegram.desktop
    
    # Desktop File
    DESKTOPFILE=%installroot%/usr/share/applications/telegram.desktop
    echo '[Desktop Entry]
    Encoding=UTF-8
    Version=1.0
    Type=Application
    Icon=telegram
    Exec=telegram
    Name=Telegram
    Comment=Telegram Client' >> $DESKTOPFILE
