name       : telegram
version    : 3.7.0
release    : 172
source     :
    - https://github.com/telegramdesktop/tdesktop/releases/download/v3.7.0/tdesktop-3.7.0-full.tar.gz : 703cf2fb7ef7216a855f18d8eeb371399a07ebe044477df08446ab03bb19369e
    - git|https://github.com/desktop-app/tg_owt.git : 63a934db1ed212ebf8aaaa20f0010dd7b0d7b396
    - git|https://gitlab.xiph.org/xiph/rnnoise.git : 7f449bf8bd3b933891d12c30112268c4090e4d59
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
optimize   :
    - function-sections
    - icf-safe
    - lto
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(absl_base)
    - pkgconfig(alsa)
    - pkgconfig(epoxy)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(hunspell)
    - pkgconfig(jemalloc)
    - pkgconfig(libavcodec)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libxxhash)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - pkgconfig(vpx)
    - pkgconfig(wayland-server)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - pkgconfig(wayland-protocols)
    - libdispatch-devel
    - plasma-wayland-protocols
    - yasm
setup      : |
    cp -r $sources/tg_owt.git tg_owt
    pushd tg_owt
        %cmake_ninja -DTG_OWT_DLOPEN_PIPEWIRE=OFF
        %ninja_build
    popd

    cp -r $sources/rnnoise.git rnnoise
    pushd rnnoise
        %autogen \
            --disable-doc \
            --disable-examples \
            --disable-shared \
            --libdir=$PWD/installed/lib \
            --prefix=$PWD/installed
        %make
        %make_install DESTDIR=/
    popd

    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$workdir/rnnoise/installed/lib/pkgconfig"
    # Building with Qt6 requires compiling and bundling kwayland at the moment. I don't want that.
    %cmake_ninja \
        -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
        -DDESKTOP_APP_DISABLE_JEMALLOC=ON \
        -DDESKTOP_APP_QT6=ON \
        -DTDESKTOP_API_HASH=8562eb11c58f218ac08ee12c32e07ece \
        -DTDESKTOP_API_ID=1080918 \
        -DTDESKTOP_LAUNCHER_BASENAME=telegramdesktop \
        -Dtg_owt_DIR=$workdir/tg_owt/solusBuildDir
build      : |
    %ninja_build
install    : |
    %ninja_install
