name       : telegram
version    : 3.3.0
release    : 163
source     :
    - https://github.com/telegramdesktop/tdesktop/releases/download/v3.3.0/tdesktop-3.3.0-full.tar.gz : 72c51d0f24c78f9362c334091fb2de71ecfe786e8d9076f9f4fca4925809489b
    - git|https://github.com/desktop-app/tg_owt.git : d5c3d43b959c7e9e7d8004b9b7fdadd12ce7d589
    - git|https://gitlab.xiph.org/xiph/rnnoise.git : 7f449bf8bd3b933891d12c30112268c4090e4d59
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
optimize   :
    - function-sections
    - icf-safe
    - lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(absl_base)
    - pkgconfig(alsa)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(hunspell)
    - pkgconfig(jemalloc)
    - pkgconfig(libavcodec)
    - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libxxhash)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - pkgconfig(vpx)
    - pkgconfig(wayland-server)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - kwayland-devel
    - yasm
rundeps    :
    - qt5-imageformats
setup      : |
    cp -r $sources/tg_owt.git tg_owt
    pushd tg_owt
        %cmake_ninja -DBUILD_SHARED_LIBS=NO
        %ninja_build
    popd

    cp -r $sources/rnnoise.git rnnoise
    pushd rnnoise
        %autogen \
            --disable-doc \
            --disable-examples \
            --disable-shared \
            --libdir=$PWD/installed/lib \
            --prefix=$PWD/installed
        %make
        %make_install DESTDIR=/
    popd

    export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$workdir/rnnoise/installed/lib/pkgconfig"
    %cmake_ninja \
        -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
        -DDESKTOP_APP_QT6=OFF \
        -DTDESKTOP_API_HASH=8562eb11c58f218ac08ee12c32e07ece \
        -DTDESKTOP_API_ID=1080918 \
        -DTDESKTOP_LAUNCHER_BASENAME=telegramdesktop \
        -Dtg_owt_DIR=$workdir/tg_owt/solusBuildDir
build      : |
    %ninja_build
install    : |
    %ninja_install
