name       : telegram
version    : 1.8.13
release    : 123
source     :
    - https://updates.tdesktop.com/tlinux/tsetup.1.8.13.tar.xz : 799255ea18b3edfe301e7a5d0ae29a836f7b5ab792aa01c8b5690a70869bedac
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xcb)
install    : |
    install -D -m 00755 Telegram $installdir/usr/bin/telegram-desktop
    install -Dm00644 $pkgfiles/telegramdesktop.desktop $installdir/usr/share/applications/telegramdesktop.desktop
    # Install icons
    for icon_size in 16 32 128 256 512
    do
        install -D -m00644 $pkgfiles/icon_${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/telegram.png
    done
