name       : telegram
version    : 2.4.2
release    : 138
source     :
    - https://github.com/telegramdesktop/tdesktop/releases/download/v2.4.2/tdesktop-2.4.2-full.tar.gz : 10c4d422d5d0fdac5dc0301c8a2acc828435cbf217b4574cf8d37e4323b68e59
    - https://github.com/desktop-app/tg_owt/archive/7a9d4bd6d9a147d15e3c8fa818a716c31f65606a/owt-7a9d4bd.tar.gz : 0c3d2476b218333ea5051b4a5364545a4a27a1d04001b1ce4843e038fba45130
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(alsa)
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(enchant-2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hunspell)
    - pkgconfig(libavcodec)
    - pkgconfig(libjpeg)
    - pkgconfig(libpulse)
    - pkgconfig(liblz4)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(opus)
    - range-v3
    - xxhash-devel
    - yasm
rundeps    :
    - qt5-imageformats
setup      : |
    mkdir tg_owt

    pushd tg_owt
        tar xf $sources/owt-* --strip-components=1
        %cmake_ninja
        %ninja_build
    popd
    
    %cmake_ninja \
        -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
        -DTDESKTOP_API_HASH=8562eb11c58f218ac08ee12c32e07ece \
        -DTDESKTOP_API_ID=1080918 \
        -DTDESKTOP_LAUNCHER_BASENAME=telegramdesktop \
        -Dtg_owt_DIR=$workdir/tg_owt/solusBuildDir
build      : |
    %ninja_build
install    : |
    %ninja_install
