name       : telegram
version    : 0.8.32
release    : 11
source     :
    - https://updates.tdesktop.com/tlinux/tsetup.0.8.32.tar.xz : fdfe3e02e1d42fe27fd6e6e47cf4fb7a1fceb63aaeb31d28de10d0cc7ecab7f1
license    : GPL-3.0
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free. 
description  : |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free. 
builddeps    : wget
install      : |
    mkdir -p %installroot%/usr/share/applications/
    mkdir -p %installroot%/opt/telegram/
    cp * %installroot%/opt/telegram/

    wget https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/Telegram/Telegram/Images.xcassets/Icon.iconset/icon_512x512.png
    mv icon_512x512.png %installroot%/opt/telegram/icon.png
    rm -f %installroot%/usr/share/applications/telegram.desktop
    
    # Desktop File
    DESKTOPFILE=%installroot%/usr/share/applications/telegram.desktop
    echo '[Desktop Entry]
    Encoding=UTF-8
    Version=1.0
    Type=Application
    Icon=/opt/telegram/icon.png
    Exec=/opt/telegram/Telegram
    Name=Telegram
    Comment=Telegram Client' >> $DESKTOPFILE
