name       : telegram
version    : 1.6.1
release    : 108
source     :
    - https://updates.tdesktop.com/tlinux/tsetup.1.6.1.tar.xz : f14863e4c875e82db39dc847e164fd363e1b2466f729ed4616c98c4bb7c2d265
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xcb)
install    : |
    install -D -m 00755 Telegram $installdir/usr/bin/telegram
    # Install icons
    for icon_size in 16 32 128 256 512
    do
        install -D -m00644 $pkgfiles/icon_${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/telegram.png
    done

    # Desktop File
    rm -f $installdir/usr/share/applications/telegram.desktop
    install -D -m00644 $pkgfiles/telegramdesktop.desktop $installdir/usr/share/applications/telegramdesktop.desktop
