name       : telegram
version    : 1.8.1
release    : 119
source     :
    - https://updates.tdesktop.com/tlinux/tsetup.1.8.1.tar.xz : 657aa9245df646fca96f2c98cf15eb9a74d96f083768e8c1e1ba81ca849d0ae4
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: |
    Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xcb)
install    : |
    install -D -m 00755 Telegram $installdir/usr/bin/telegram-desktop
    install -Dm00644 $pkgfiles/telegramdesktop.desktop $installdir/usr/share/applications/telegramdesktop.desktop
    # Install icons
    for icon_size in 16 32 128 256 512
    do
        install -D -m00644 $pkgfiles/icon_${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/telegram.png
    done
