name       : telegram
version    : 1.1.7
release    : 67
source     :
    - https://updates.tdesktop.com/tlinux/tsetup.1.1.7.tar.xz : c0a2d38219f2923294fda46fb11da868523808abccd88f60c979a32828b9473e
    - https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/Telegram/Telegram/Images.xcassets/Icon.iconset/icon_16x16.png : fc052d1e28b68761bfb6c30ff012e54a4bba0311fc3fc470c728d028c33e9d9f
    - https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/Telegram/Telegram/Images.xcassets/Icon.iconset/icon_32x32.png : 8ae874ada23687c95cbcfe7cfa4cbe1c37f097d9c96e5a836c20109d976a86c7
    - https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/Telegram/Telegram/Images.xcassets/Icon.iconset/icon_128x128.png : 83e3e8eeecadcb3429704626d4ac80ef61ef4e06ba2c6ca2b105a4a436f33032
    - https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/Telegram/Telegram/Images.xcassets/Icon.iconset/icon_256x256.png : 871f2a6d3bd9d657f8379196e51fd3117c1586e0042e9e993ae138f78b2bcd76
    - https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/Telegram/Telegram/Images.xcassets/Icon.iconset/icon_512x512.png : a9eb77ca5a428b32f6e01f62b859cce788c4c9a170dc2cd080800a9de59faa3d
license    : GPL-3.0
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s
    super fast, simple and free.
description: Telegram is a messaging app with a focus on speed and security, it’s
    super fast, simple and free.
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xcb)
install    : |
    install -D -m 00755 Telegram $installdir/usr/bin/telegram
    # Install icons
    for icon_size in 16 32 128 256 512
    do
        install -D -m00644 $sources/icon_${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/telegram.png
    done

    # Desktop File
    rm -f $installdir/usr/share/applications/telegram.desktop
    install -D -m00644 $pkgfiles/telegram.desktop $installdir/usr/share/applications/telegram.desktop
