name       : telegram
version    : 0.9.56
release    : 47
source     :
    - https://updates.tdesktop.com/tlinux/tsetup.0.9.56.tar.xz : e214c60771c76b81ad65e175c68345d8e9df043f68944063babd395fcc85f6c3
license    : GPL-3.0
component  : network.im
summary    : Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
description: Telegram is a messaging app with a focus on speed and security, it’s super fast, simple and free.
builddeps  : wget
install    : |
    install -Dm755 Telegram %installroot%/usr/bin/telegram

    # Create icon directories

    iconlist=(icon_16x16.png icon_32x32.png icon_128x128.png icon_256x256.png icon_512x512.png)

    # Fetch all icons

    for icon in "${iconlist[@]}"
    do
        wget https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/Telegram/Telegram/Images.xcassets/Icon.iconset/$icon

        icondir=${icon/icon_/}
        icondir=${icondir/.png/}

        install -Dm644 $icon %installroot%/usr/share/icons/hicolor/$icondir/apps/telegram.png
    done

    # Desktop File
    rm -f %installroot%/usr/share/applications/telegram.desktop
    install -Dm644 $pkgfiles/telegram.desktop %installroot%/usr/share/applications/telegram.desktop
